version: '3.8'

services:
  personal-website:
    image: kaiza20232064/finall_lab:latest
    container_name: personal-website
    ports:
      - "8080:80"
    restart: always
  
  todo-app:
    image: dockersamples/101-todo-app:latest
    container_name: todo-app
    ports:
      - "8081:3000"
    restart: always