version: '3.8'

services:
  personal-website:
    build: .
    container_name: personal-website
    ports:
      - "8082:80"
    restart: always
  
  todo-app:
    image: dockersamples/101-todo-app:latest
    container_name: todo-app
    ports:
      - "8083:3000"
    restart: always
    environment:
      - NODE_ENV=production