version: '3.8'

services:
  personal-website:
    image: your-dockerhub-username/lab12-app:latest
    container_name: personal-website
    ports:
      - "8080:80"
    restart: always
  
  todo-app:
    image: docker/getting-started
    container_name: todo-app
    ports:
      - "8081:80"
    restart: always